### ISSUE TITLE
[06/11] FRONT - TELA HOME

### ISSUE THREAD

**Issue by Silvestrinih03** [Silvestrinih03/PI4-BAGVIEW#8]
Deve exibir mapa e as opções de menu

1. Alugar tag
2. Opção de configurações
3. Opção de logout

**Comment by Kenji1655** [comment]
Grande parte finalizada, sendo necessario apenas ajustes finos
- Adicionar novas imagens na home da página
- Alterar icones da descrição
- remover sombra das perguntas frequentes
- Arrumar o header para fazer animação de troca de cor e logo
